name: Android APK Release

on:
  push:
    tags: ['v*']   # ex.: git tag v1.0.0 && git push origin v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # ───────────────────────── 1. Code ─────────────────────────
    - uses: actions/checkout@v4

    # ───────────────────────── 2. Java 17 ──────────────────────
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    # ───────────────────────── 3. SDK Android ──────────────────
    #      ↳ API 33 + Build-Tools 33.0.2 (dernière stable)
    - uses: android-actions/setup-android@v3
      with:
        packages: >-
          platform-tools
          platforms;android-33
          build-tools;33.0.2

    # ── 4. Vars d’environnement pour NativeScript & Gradle ──
    - run: |
        echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV

    # ───────────────────────── 5. Node & NS CLI ────────────────
    - uses: actions/setup-node@v4
      with:
        node-version: '18'

    - run: npm install -g nativescript
    - run: npm ci

    # ──────────────────────── 6. Keystore signé ────────────────
    - run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > cogwalk-release-key.jks

    # ───────────────────────── 7. Build APK ────────────────────
    - run: |
        ns build android \
          --release \
          --key-store-path cogwalk-release-key.jks \
          --key-store-password "${{ secrets.KEYSTORE_PASSWORD }}" \
          --key-store-alias "${{ secrets.KEY_ALIAS }}" \
          --key-store-alias-password "${{ secrets.KEY_PASSWORD }}"

    # ─────────────────────── 8. Renomme l’APK ──────────────────
    - run: |
        mv platforms/android/app/build/outputs/apk/release/app-release.apk \
           cogwalk-${{ github.ref_name }}.apk

    # ──────────────── 9. Publie dans GitHub Releases ───────────
    - uses: softprops/action-gh-release@v2
      with:
        files: cogwalk-${{ github.ref_name }}.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
