name: Android APK Release

on:
  push:
    tags:
      - 'v*'            # déclenché sur v1.0.0, v1.0.1…

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # 1. JDK 17 – requis par les command-line tools 16.0
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        # une SEULE ligne :
        packages: 'platform-tools platforms;android-33 build-tools;33.0.0'


    # 2. SDK Android complet (plate-forme + build-tools)
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        packages: |
          platform-tools
          platforms;android-34
          build-tools;34.0.0

    # 3. ANDROID_HOME pour NativeScript
    - run: echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV

    # 4. Node + NativeScript CLI
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
    - run: npm install -g nativescript
    - run: npm ci          # dépendances du projet

    # 5. Décodage du keystore stocké en secret
    - run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > cogwalk-release-key.jks

    # 6. Build APK signé
    - run: |
        ns build android \
          --release \
          --key-store-path cogwalk-release-key.jks \
          --key-store-password "${{ secrets.KEYSTORE_PASSWORD }}" \
          --key-store-alias "${{ secrets.KEY_ALIAS }}" \
          --key-store-alias-password "${{ secrets.KEY_PASSWORD }}"

    # 7. Renomme et publie l’APK dans la Release GitHub
    - run: mv platforms/android/app/build/outputs/apk/release/app-release.apk cogwalk-${{ github.ref_name }}.apk
    - uses: softprops/action-gh-release@v2
      with:
        files: cogwalk-${{ github.ref_name }}.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
