name: Android APK Release

# ─────────────────────────────────────────────────────────────
# Déclenche le workflow à chaque tag commençant par « v »
#   ex. : git tag v1.0.0 && git push origin v1.0.0
# ─────────────────────────────────────────────────────────────
on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Récupération du dépôt
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Java 17 (compatible AGP 8 et tools 16.0)
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    # 3. SDK Android complet
    #    → une SEULE ligne grâce au chevron `>-`
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        packages: >-
          platform-tools
          platforms;android-33
          build-tools;33.0.0

    # 4. Expose ANDROID_HOME pour NativeScript
    - name: Export ANDROID_HOME
      run: echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV

    # 5. Node.js & NativeScript CLI
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install NativeScript CLI
      run: npm install -g nativescript

    - name: Install project dependencies
      run: npm ci

    # 6. Recrée le keystore depuis le secret encodé en base64
    - name: Decode keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > cogwalk-release-key.jks

    # 7. Build APK signé
    - name: Build signed APK
      run: |
        ns build android \
          --release \
          --key-store-path cogwalk-release-key.jks \
          --key-store-password "${{ secrets.KEYSTORE_PASSWORD }}" \
          --key-store-alias "${{ secrets.KEY_ALIAS }}" \
          --key-store-alias-password "${{ secrets.KEY_PASSWORD }}"

    # 8. Renomme l’APK pour l’attacher à la release
    - name: Rename APK
      run: |
        mv platforms/android/app/build/outputs/apk/release/app-release.apk \
           cogwalk-${{ github.ref_name }}.apk

    # 9. Publie l’APK dans la Release GitHub
    - name: Publish to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: cogwalk-${{ github.ref_name }}.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
